package br.com.etechoracio.enums.ExFisico;

public enum ExercicioEnum {
    SupinoReto,
    SupinoInclinado,
    Crucifixo,
    PeckDeck,
    DesenvolvimentoOmbros,
    ElevacaoLateral,
    ElevacaoFrontal,
    RemadaCurvada,
    PuxadaPulley,
    LevantamentoTerra,
    EncolhimentoTrapezio,
    RoscaDireta,
    RoscaMartelo,
    TricepsCorda,
    TricepsTesta,
    AgachamentoLivre,
    LegPress,
    Extensora,
    Flexora,
    Stiff,
    Afundo,
    ElevacaoPelvica,
    CadeiraAbdutora,
    CadeiraAdutora,
    GemeosEmPe,
    GemeosSentado,
    AbdominalSupra,
    AbdominalInfra,
    PranchaAbdominal,
    LombarBancoRomano;
}
